### ISSUE TITLE
图文部署教程

### ISSUE THREAD

**Issue by BlueSkyXN** [qkqpttgf/OneManager-cfworkerskv#1]
https://www.blueskyxn.com/202102/3903.html

**Comment by qkqpttgf** [comment]
我可以责令你把里面的github地址改成我的吧？

**Comment by BlueSkyXN** [comment]
> 我可以责令你把里面的github地址改成我的吧？

已改QAQ【等待刷新缓存】

**Comment by qkqpttgf** [comment]
> > 我可以责令你把里面的github地址改成我的吧？
> 
> 已改QAQ【等待刷新缓存】

缓存太久了吧！

**Comment by BlueSkyXN** [comment]
> > > 我可以责令你把里面的github地址改成我的吧？
> > 
> > 
> > 已改QAQ【等待刷新缓存】
> 
> 缓存太久了吧！

[img]https://p.pstatp.com/origin/138230002618209de5290[/img]
国内缓存刷新慢，国外应该刷好了啊
