### ISSUE TITLE
在PHP版本能添加的盘在这个版本添加不了

### ISSUE THREAD

**Issue by gsxbxsg** [qkqpttgf/OneManager-cfworkerskv#11]
{"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '734ef928-d74c-4555-8d1b-d942fa0a1a41'.\r\nTrace ID: bc6ca77d-7e66-4b8d-954d-8c3f62a40f00\r\nCorrelation ID: e86bc24d-ad70-4946-b6ce-f62ee209d70b\r\nTimestamp: 2022-07-18 04:58:09Z","error_codes":[7000215],"timestamp":"2022-07-18 04:58:09Z","trace_id":"bc6ca77d-7e66-4b8d-954d-8c3f62a40f00","correlation_id":"e86bc24d-ad70-4946-b6ce-f62ee209d70b","error_uri":"https://login.microsoftonline.com/error?code=7000215"}

**Comment by qkqpttgf** [comment]
Invalid client secret provided，

仔细读一下嘛……

secret过期了呗，你从php这边复制过去，或者用你自己的client。

**Comment by gsxbxsg** [comment]
用的是a1账号，自己开不了client怎么办呢？

**Comment by qkqpttgf** [comment]
> 用的是a1账号，自己开不了client怎么办呢？

???你只看后半句话？？

**Comment by gsxbxsg** [comment]
为什么你的client ID和client secret是通用的？
是因为添加 MPN ID 来验证发布者嘛？

**Comment by gsxbxsg** [comment]
我自己注册的应用会显示未验证

**Comment by qkqpttgf** [comment]
> 为什么你的client ID和client secret是通用的？ 是因为添加 MPN ID 来验证发布者嘛？

可能我创建client的时间早了那么一点点。

**Comment by gsxbxsg** [comment]
好的，谢谢！
