### ISSUE TITLE
Client secret过期，安装失败求助

### ISSUE THREAD

**Issue by barton0426** [qkqpttgf/OneManager-cfworkerskv#12]
{"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '734ef928-d74c-4555-8d1b-d942fa0a1a41'.\r\nTrace ID: 16ba188c-9981-427c-89ca-92c05b482600\r\nCorrelation ID: 4d6a999d-b728-484e-b7b9-a196431aac7c\r\nTimestamp: 2022-09-01 02:40:11Z","error_codes":[7000215],"timestamp":"2022-09-01 02:40:11Z","trace_id":"16ba188c-9981-427c-89ca-92c05b482600","correlation_id":"4d6a999d-b728-484e-b7b9-a196431aac7c","error_uri":"https://login.microsoftonline.com/error?code=7000215"}

**Comment by qkqpttgf** [comment]
默认secret过期了，因为我没更新，你从OM复制过来，或者用你自己的client。
