### ISSUE TITLE
一直报这个错

### ISSUE THREAD

**Issue by 54nzg** [qkqpttgf/OneManager-cfworkerskv#6]
{"error":{"code":"BadRequest","message":"Tenant does not have a SPO license.","innerError":{"date":"2021-10-13T16:00:27","request-id":"4f39138b-0a17-44ed-9c89-beac7651e8cb","client-request-id":"4f39138b-0a17-44ed-9c89-beac7651e8cb"}}}

**Comment by qkqpttgf** [comment]
请自己翻译
提醒，你帐号问题，去官网登录看看你文件吧！
